config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, only: [:index, :show, :new, :create]

  get '/', :to => 'boards#new'

  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    has_many :mines

    # name & email must exist
    validates :name, :email, presence: true

    # board name must be unique
    validates :name, uniqueness: true

    # h & w are positive integers
    validates :height, :width, :numericality => { :greater_than_or_equal_to => 0 }

end

app/models/mine.rb
class Mine < ApplicationRecord
  belongs_to :board

  def self.generate_mine_values(height, width, mine_count, board_id)
    # this method should return a 2d array of objs representing "the state of the board before the game starts"

    # create record of selected mine locations
    mine_locations = {}

    mine_count.times do
        # grab random coordinates
        randomX = rand(1..width)
        randomY = rand(1..height)

        # if these coords have already been picked, pick again
        while (mine_locations["X#{randomX}Y#{randomY}"]) do
            randomX = rand(1..width)
            randomY = rand(1..height)
        end

        # once we get fresh ones, add them to the record
        mine_locations["X#{randomX}Y#{randomY}"] = {"x": randomX, "y": randomY}

        # and save to DB
        Mine.create({"x": randomX, "y": randomY, "board_id"=>board_id})
    end

    mine_locations
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    
    def index
        # pluck will do a select of the values wanted, instead of loading whole model in
        @emails = Board.pluck(:email).uniq
        
        if params[:email]
            @boards = Board.all.filter do |b| b.email === params[:email] end
        else
            @boards = Board.all
        end
    end
    
    def create
        # destructure params
        height, width, mines, email, name = board_params.values_at(:height, :width, :mines, :email, :name)
        
        # create board instance
        @new_board = Board.new({
            name:name, 
            email:email, 
            height:height,
            width:width,
        })

        if @new_board.save

            # if the board's valid, create mine instances by passing numbers to model method to generate 2d array board format
            Mine.generate_mine_values(height.to_i, width.to_i, mines.to_i, @new_board.id)

            @board = BoardSerializer.new(@new_board)
            redirect_to action: "show", id: @new_board.id
            
        else
            # if board's not valid, use render :new so it populates the form with the board data that was sent through on first attempt
            flash[:error] = @new_board.errors.full_messages.to_sentence        
            @most_recent_boards = Board.last(10).reverse
            @new_board      
            render :new
        end
    end

    def new
        @most_recent_boards = Board.last(10).reverse
        @board = Board.new
    end

    def show
        board_selected = Board.find(params[:id])
        @board = BoardSerializer.new(board_selected)
    end

    private
    def board_params
        params.require(:board).permit(:name, :email, :width, :height, :mines)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<div class='box-card'>
    <h1>Viewing Boards</h1>
    <p>To filter, select creator below...</p>

    <%= form_with url: "boards", method: :get do |f| %>
    <%=select_tag "email", options_from_collection_for_select(@emails, :to_str, :to_str)%>
    <%= f.submit  "Show Boards"%>
    <% end  %>

    <ul class='no-bullets'>
        <%@boards.each do |board|%>
        <li>
            <%= link_to board.name, board%>, <%=board.height%> x <%=board.width%>
        </li>
        <%end%>
    </ul>
    <p>
        <%= link_to "Clear Filter", boards_path%>
        <br />
        <%= link_to "Create Your Own Board", new_board_path%>
    </p>
</div>

app/views/boards/new.html.erb
<div class='box-card'>
    <h2>New Board Form:</h2>

    <%if flash[:error]%>
        <p> <span class='error'>Bummer!</span> Your submission resulted in the following error(s): </p>
        <span class='error'>
        <%=flash[:error]%>
        </span>
        <p/>
    <%end%>
    <%= form_with model: @board do |f| %>
        <%= f.label :email, "Creator Email:" %>
        <%= f.text_field :email %>
        <p/>
        <%= f.label :name, "Board Name:" %>
        <%= f.text_field :name %>
        <p>____________________________</p>
        <div class='bold'>Board Dimensions</div>
        <p/>
        <%= f.label :height, "Height and width (in number of squares):" %>
        <p />
        <%= f.number_field :height, placeholder: "height"%> X
        <%= f.number_field :width, placeholder: "width"%>
        <br/>
        <p />
        <%= f.label :mines, "Number of mines:" %>
        <%= f.number_field :mines %> 
        <p />
        <%=f.submit "Generate Board"%>
    <%end %>
</div>
<%if @most_recent_boards.length > 0%>
    <div class='top-ten'>
        <p>____________________________</p>
            <h2>Most Recently Created Boards:</h2>
            <ol>
                <%@most_recent_boards.each do |board|%>
                    <li>
                        <%=link_to board.name, board%>, created by <%=board.email%> on <%=board.created_at.to_date%>
                    </li>
                <%end%>
            </ol>
        <%= link_to "View All Generated Boards", boards_path%>
    </div>
<%end%>

app/views/boards/show.html.erb
<div class='box-card'>
    <h1>Currently Viewing <%=@board.object.name%></h1>
    <h2>...a board made by <%=@board.object.email%></h2>
    <%if @board.object.height*@board.object.width < 1000000 %>
    <ul class='no-bullets'>
        <%@board.object.height.times do |row|%>
        <li>
            <%@board.object.width.times do |col|%>
            <%if @board.hashed_mines["X#{col}Y#{row}"]%>
            💣
            <%else%>
            ◻️
            <%end%>
            <%end%>
        </li>
        <%end%>
    </ul>
    <%else%>
    <p>Board dimensions: <%=@board.object.height%> X <%=@board.object.width%></p>
    <div>...for a total of <%=@board.object.height*@board.object.width%> spaces. </div>
    <p>
        Mine locations are as follows:

    <ul>
        <%@board.hashed_mines.each do |name, coords|%>
        <li>
            <%=name%>
        </li>
        <%end%>
    </ul>
    </p>
    <%end%>
    <%= link_to "View All Boards", boards_path%>
    <%= link_to "Create a New Board", new_board_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper Generator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>